##
#The sequence of triangle numbers is generated by adding the natural numbers
#Example: 7th triangle number 1+2+3+4+5+6+7 = 28
#28 has over 5 divisors: 1,2,4,7,14,28
#Find the first triangle number that has over 500 divisors
##

from pe5_SCM import define_factors

i = 1
tri = 1
u = 0
while u < 500:
	tri = sum(range(1, i))
	u = len(define_factors(tri))
	i += 1

print tri
	